// ============================================================================
//  GestiPerso — Icon registry
// ----------------------------------------------------------------------------
//  One icon set for the whole product (Lucide, through `react-icons`) exposed
//  under product names so a screen never imports the icon library directly.
//  Swapping the icon family later means editing this file only.
// ============================================================================

export {
  LuAlarmClock as Alarm,
  LuArrowLeft as ArrowLeft,
  LuArrowRight as ArrowRight,
  LuArrowUpRight as ArrowUpRight,
  LuAward as Award,
  LuBadgeCheck as BadgeCheck,
  LuChartBar as ChartBar,
  LuBell as Bell,
  LuCake as BirthdayCake,
  LuBriefcase as Briefcase,
  LuBuilding2 as Building,
  LuCalendarCheck as CalendarCheck,
  LuCalendarDays as Calendar,
  LuChartColumn as ChartColumn,
  LuChartPie as ChartPie,
  LuCheck as Check,
  LuCheckCheck as CheckAll,
  LuChevronDown as ChevronDown,
  LuChevronLeft as ChevronLeft,
  LuChevronRight as ChevronRight,
  LuChevronUp as ChevronUp,
  LuCircleAlert as AlertCircle,
  LuCircleCheck as CheckCircle,
  LuCircleHelp as Help,
  LuCircleX as XCircle,
  LuClipboardCheck as ClipboardCheck,
  LuClipboardList as ClipboardList,
  LuClock as Clock,
  LuContrast as Contrast,
  LuDownload as Download,
  LuEye as Eye,
  LuExternalLink as ExternalLink,
  LuFileCheck as FileCheck,
  LuFileText as FileText,
  LuFilter as Filter,
  LuFingerprint as Fingerprint,
  LuFolder as Folder,
  LuFolderOpen as FolderOpen,
  LuGauge as Gauge,
  LuGraduationCap as GraduationCap,
  LuHourglass as Hourglass,
  LuInbox as Inbox,
  LuInfo as Info,
  LuKeyRound as Key,
  LuLandmark as Landmark,
  LuLaptop as Laptop,
  LuList as ListIcon,
  LuLoaderCircle as LoaderCircle,
  LuLockKeyhole as Lock,
  LuLogOut as Logout,
  LuMail as Mail,
  LuMapPin as MapPin,
  LuMenu as Menu,
  LuMessageSquare as MessageSquare,
  LuMonitor as Monitor,
  LuMoon as Moon,
  LuNotebookPen as Notes,
  LuPanelLeftClose as PanelLeftClose,
  LuPanelLeftOpen as PanelLeftOpen,
  LuPencil as Pencil,
  LuPhone as Phone,
  LuPlus as Plus,
  LuPrinter as Printer,
  LuRefreshCw as Refresh,
  LuRotateCw as Reload,
  LuSave as Save,
  LuSearch as Search,
  LuSend as Send,
  LuSettings as Settings,
  LuShieldCheck as ShieldCheck,
  LuSparkles as Sparkles,
  LuStethoscope as Stethoscope,
  LuSun as Sun,
  LuSunMedium as SunMedium,
  LuTrash2 as Trash,
  LuTrendingDown as TrendingDown,
  LuTrendingUp as TrendingUp,
  LuTriangleAlert as Warning,
  LuUpload as Upload,
  LuUser as User,
  LuUserPlus as UserPlus,
  LuUsers as Users,
  LuX as Close,
} from 'react-icons/lu'
